CREATE TABLE GEFDATABASE.Course (ID_COURSE INTEGER NOT NULL,
CODE VARCHAR(5) NOT NULL,
CREDIT INTEGER NOT NULL,
NAME VARCHAR(20) NOT NULL,
MODULE INTEGER NOT NULL,
PRIMARY KEY (ID));

CREATE TABLE GEFDATABASE.StudentsClass (ID_STUDENTSCLASS INTEGER NOT NULL,

);